/**
 * Rustwire — client-side renderer for the niche-intel dashboard.
 * Fetches data/feed.json (generated by the GitHub Actions pipeline) and
 * renders the TL;DR section, the discussion feed, and the source filters.
 */

const FEED_URL = "data/feed.json";

const SOURCE_LABELS = {
  reddit: "Reddit",
  hackernews: "HN",
  lobsters: "Lobsters",
  rss: "Blog",
};

const state = {
  data: null,
  filter: "all",
};

/* ---------- Fetch ---------- */
async function loadFeed() {
  try {
    const res = await fetch(`${FEED_URL}?t=${Date.now()}`, { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    state.data = data;
    renderAll();
    setStatus("ok");
  } catch (err) {
    console.error("Feed load failed:", err);
    setStatus("error");
    showError();
  }
}

/* ---------- Render: header meta ---------- */
function setStatus(kind) {
  const dot = document.getElementById("status-dot");
  dot.classList.remove("ok", "error");
  if (kind === "ok") dot.classList.add("ok");
  if (kind === "error") dot.classList.add("error");
  dot.title = kind === "ok" ? "Feed loaded" : "Feed unavailable";
}

function renderUpdated() {
  const el = document.getElementById("updated-time");
  if (!state.data?.updated_at) {
    el.textContent = "never";
    return;
  }
  const d = new Date(state.data.updated_at);
  el.dateTime = state.data.updated_at;
  el.textContent = relativeTime(d);
  el.title = d.toLocaleString();
}

function relativeTime(date) {
  const diff = (Date.now() - date.getTime()) / 1000;
  if (diff < 60) return "just now";
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
  return `${Math.floor(diff / 86400)}d ago`;
}

/* ---------- Render: TL;DR cards ---------- */
function renderTldr() {
  const grid = document.getElementById("tldr-grid");
  const items = state.data?.tldr ?? [];

  if (items.length === 0) {
    grid.innerHTML = `
      <div class="empty-state" style="grid-column: 1 / -1;">
        <p>No summarized items yet. The next pipeline run will populate this section.</p>
      </div>`;
    return;
  }

  grid.innerHTML = items.map((item) => {
    const bullets = (item.bullets || [])
      .map((b) => `<li>${escapeHtml(b)}</li>`)
      .join("");
    const sourceLabel = SOURCE_LABELS[item.source] || item.source;
    const metaBits = [];
    if (typeof item.score === "number") metaBits.push(`▲ ${item.score}`);
    if (typeof item.comments === "number") metaBits.push(`💬 ${item.comments}`);
    if (item.author) metaBits.push(`by ${escapeHtml(item.author)}`);

    return `
      <article class="tldr-card">
        <div class="tldr-card-head">
          <span class="source-tag ${item.source}">${sourceLabel}</span>
          <span>${escapeHtml(item.subsource || "")}</span>
        </div>
        <h3 class="tldr-title">
          <a href="${escapeAttr(item.url)}" target="_blank" rel="noopener">${escapeHtml(item.title)}</a>
        </h3>
        <ul class="tldr-bullets">${bullets}</ul>
        <div class="tldr-card-meta">
          ${metaBits.map((b) => `<span>${b}</span>`).join("")}
        </div>
      </article>`;
  }).join("");
}

/* ---------- Render: feed ---------- */
function renderFeed() {
  const list = document.getElementById("feed-list");
  const empty = document.getElementById("empty-state");
  const error = document.getElementById("error-state");
  error.classList.add("hidden");

  const all = state.data?.discussions ?? [];
  const items = state.filter === "all"
    ? all
    : all.filter((i) => i.source === state.filter);

  if (items.length === 0) {
    list.innerHTML = "";
    empty.classList.remove("hidden");
    return;
  }
  empty.classList.add("hidden");

  list.innerHTML = items.map((item) => {
    const sourceLabel = SOURCE_LABELS[item.source] || item.source;
    const meta = [`<span class="source-tag ${item.source}">${sourceLabel}</span>`];
    if (item.subsource) meta.push(`<span>${escapeHtml(item.subsource)}</span>`);
    if (item.published) meta.push(`<span>${relativeTime(new Date(item.published))}</span>`);
    if (item.author) meta.push(`<span>by ${escapeHtml(item.author)}</span>`);

    const discussLink = item.discuss_url
      ? `<a class="feed-discuss" href="${escapeAttr(item.discuss_url)}" target="_blank" rel="noopener">💬 ${item.comments ?? 0}</a>`
      : "";

    const score = typeof item.score === "number" ? item.score : "—";

    return `
      <li class="feed-item">
        <div class="feed-score">${score}<small>SCORE</small></div>
        <div class="feed-main">
          <a class="feed-title" href="${escapeAttr(item.url)}" target="_blank" rel="noopener">${escapeHtml(item.title)}</a>
          <div class="feed-meta">${meta.join("")}</div>
        </div>
        ${discussLink}
      </li>`;
  }).join("");
}

/* ---------- Render: error ---------- */
function showError() {
  document.getElementById("tldr-grid").innerHTML = "";
  document.getElementById("feed-list").innerHTML = "";
  document.getElementById("error-state").classList.remove("hidden");
  document.getElementById("empty-state").classList.add("hidden");
}

function renderAll() {
  renderUpdated();
  renderTldr();
  renderFeed();
}

/* ---------- Filters ---------- */
function attachFilters() {
  document.querySelectorAll(".filter-chip").forEach((btn) => {
    btn.addEventListener("click", () => {
      document.querySelectorAll(".filter-chip").forEach((b) => {
        b.classList.remove("active");
        b.setAttribute("aria-selected", "false");
      });
      btn.classList.add("active");
      btn.setAttribute("aria-selected", "true");
      state.filter = btn.dataset.source;
      renderFeed();
    });
  });
}

/* ---------- Helpers ---------- */
function escapeHtml(s) {
  if (s == null) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function escapeAttr(s) {
  return escapeHtml(s).replace(/`/g, "&#096;");
}

/* ---------- Init ---------- */
attachFilters();
loadFeed();
